sfdcwebapp:
  image: jigsheth57/sfdcwebapp:2.0
  environment:
    - SPRING_PROFILES_ACTIVE=local
  ports:
   - "9090:9090"
  links:
   - configserver
   - discovery
   - sfdcapigateway
smoketest:
  image: jigsheth57/smoketest:latest
  environment:
    - "SFDC_API_GATEWAY_BASEURL=http://sfdcapigateway:9011"
  links:
   - sfdcapigateway
#dataloadservice:
#  image: jigsheth57/dataloadservice:2.0
#  environment:
#    - SPRING_PROFILES_ACTIVE=local
#    - SPRING_REDIS_HOST=redis
#  ports:
#   - "9004:9004"
#  links:
#   - redis
sfdcapigateway:
  image: jigsheth57/sfdcapigateway:2.0
  environment:
    - SPRING_PROFILES_ACTIVE=local
    - SPRING_RABBITMQ_HOST=rabbitmq
    - SPRING_RABBITMQ_PORT=5672
    - SPRING_RABBITMQ_USERNAME=guest
    - SPRING_RABBITMQ_PASSWORD=guest
  ports:
   - "9011:9011"
  links:
   - configserver
   - discovery
   - hystrixdashboard
   - rabbitmq
   - redis
   - authservice
   - accountservice
   - contactservice
   - opportunityservice
opportunityservice:
  image: jigsheth57/opportunityservice:2.0
  environment:
    - SPRING_PROFILES_ACTIVE=local
    - SPRING_RABBITMQ_HOST=rabbitmq
    - SPRING_RABBITMQ_PORT=5672
    - SPRING_RABBITMQ_USERNAME=guest
    - SPRING_RABBITMQ_PASSWORD=guest
  ports:
   - "9003:9003"
  links:
   - configserver
   - discovery
   - hystrixdashboard
   - rabbitmq
   - authservice
   - redis
contactservice:
  image: jigsheth57/contactservice:2.0
  environment:
    - SPRING_PROFILES_ACTIVE=local
    - SPRING_RABBITMQ_HOST=rabbitmq
    - SPRING_RABBITMQ_PORT=5672
    - SPRING_RABBITMQ_USERNAME=guest
    - SPRING_RABBITMQ_PASSWORD=guest
  ports:
   - "9002:9002"
  links:
   - configserver
   - discovery
   - hystrixdashboard
   - rabbitmq
   - authservice
   - redis
accountservice:
  image: jigsheth57/accountservice:2.0
  environment:
    - SPRING_PROFILES_ACTIVE=local
    - SPRING_RABBITMQ_HOST=rabbitmq
    - SPRING_RABBITMQ_PORT=5672
    - SPRING_RABBITMQ_USERNAME=guest
    - SPRING_RABBITMQ_PASSWORD=guest
  ports:
   - "9001:9001"
  links:
   - configserver
   - discovery
   - hystrixdashboard
   - rabbitmq
   - authservice
   - redis
authservice:
  image: jigsheth57/authservice:2.0
  environment:
    - SPRING_PROFILES_ACTIVE=local
  ports:
   - "9000:9000"
  links:
   - configserver
   - discovery
   - redis
hystrixdashboard:
  image: jigsheth57/hystrixdashboard:2.0
  environment:
    - SPRING_PROFILES_ACTIVE=local
    - SPRING_RABBITMQ_HOST=rabbitmq
    - SPRING_RABBITMQ_PORT=5672
    - SPRING_RABBITMQ_USERNAME=guest
    - SPRING_RABBITMQ_PASSWORD=guest
  ports:
   - "7979:7979"
  links:
   - configserver
   - discovery
   - rabbitmq
turbine:
  image: jigsheth57/turbine:latest
  environment:
    - TURBINE_STREAMS=http://accountservice:9001/manage/hystrix.stream http://contactservice:9002/manage/hystrix.stream http://opportunityservice:9003/manage/hystrix.stream http://sfdcapigateway:9011/manage/hystrix.stream
  ports:
   - "8000:8000"
  links:
   - sfdcapigateway
   - accountservice
   - opportunityservice
   - contactservice
discovery:
  image: jigsheth57/eurekaserver:2.0
  ports:
   - "8761:8761"
configserver:
  image: jigsheth57/configserver:2.0
  environment:
    - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/jigsheth57/config-repo
  ports:
   - "8888:8888"
  links:
   - discovery
rabbitmq:
  image: rabbitmq:3-management
  ports:
  - "15671:15671"
  - "15672:15672"
  - "5672:5672"
  - "4369:4369"
  - "5671:5671"
  - "25672:25672"
redis:
  image: redis:latest
  ports:
    - "6379:6379"
