redis:
  image: redis:latest
  ports:
    - "6379:6379"

rabbitmq:
  image: rabbitmq:3-management
  ports:
  - "15671:15671"
  - "15672:15672"
  - "5672:5672"
  - "4369:4369"
  - "5671:5671"
  - "25672:25672"

discovery:
  image: jigsheth57/eurekaserver:2.0
  ports:
   - "8761:8761"

configserver:
  image: jigsheth57/configserver:2.0
  environment:
    - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/jigsheth57/config-repo
  ports:
   - "8888:8888"
  links:
   - discovery

hystrixdashboard:
  image: jigsheth57/hystrixdashboard:2.0
  environment:
    - SPRING_PROFILES_ACTIVE=local
    - SPRING_RABBITMQ_HOST=rabbitmq
    - SPRING_RABBITMQ_PORT=5672
    - SPRING_RABBITMQ_USERNAME=guest
    - SPRING_RABBITMQ_PASSWORD=guest
  ports:
   - "7979:7979"
  links:
   - configserver
   - discovery
   - rabbitmq

authservice:
  image: jigsheth57/authservice:2.0
  environment:
    - PORT=9000
    - SPRING_PROFILES_ACTIVE=local
    - SPRING_RABBITMQ_HOST=rabbitmq
    - SPRING_RABBITMQ_PORT=5672
    - SPRING_RABBITMQ_USERNAME=guest
    - SPRING_RABBITMQ_PASSWORD=guest
  ports:
   - "9000:9000"
  links:
   - configserver
   - discovery
   - rabbitmq
   - redis
