---
timeout: 180
instances: 1
memory: 512M
env:
    SPRING_PROFILES_DEFAULT: cloud
    SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/jigsheth57/config-repo

applications:
- name: configserver
  path: configServer/target/configServer-0.0.1-SNAPSHOT.jar
  services: [ p-service-registry ]
